version: "3.9"
networks:
  sc_statistic:
    driver: bridge
services:
  app: 
    container_name: sc_statistic_app
    build:
      context: ../
      dockerfile: ./SC_statistic/Dockerfile
    ports:
      - "80:80"
    networks:
      - sc_statistic
    depends_on:
      - postgres_db
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
  postgres_db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: SC_statistic_db
    ports:
      - "5432:5432"
    networks:
      - sc_statistic
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: