version: '3.9'

services:
  app:
    #image: mcr.microsoft.com/dotnet/aspnet:6.0 
    container_name: SC_stat_app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"  
    networks:
      - deploy-guide-dev
    depends_on:
      - db

    #environment:
     # - PROJECT_PATH=/app/SC_statistic  # Относительный путь к проекту
    #volumes:
    #  - ./AspNetCoreApp:/app/SC_statistic  # Используйте относительный путь к вашему проекту ASP.NET Core

  db:
    image: mysql:8.0.33
    container_name: mysql_db
    restart: always
    ports: 
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: Rb,thhnhjkm2000  
      MYSQL_DATABASE: st_statistic_db  
    volumes:
      - mysql-data:/var/lib/mysql/data